-- Drop existing tables if they exist
DROP TABLE IF EXISTS 
    PATIENT, BOOKING, VACCINATION, APPOINTMENT, CENTRE, TIMING, DOCTOR, MANAGER_HISTORY;

-- Create Patient Table
CREATE TABLE PATIENT (
    PAT_ID NUMERIC,
    PAT_NAME VARCHAR(10),
    PAT_ADD VARCHAR(16),
    PAT_NUM CHAR(8),
    PRIMARY KEY (PAT_ID)
);

-- Create Booking Table
CREATE TABLE BOOKING (
    BOOKING_ID NUMERIC,
    PAT_ID NUMERIC,
    DOC_ID NUMERIC,
    BOOKING_DATE DATE,
    PRIMARY KEY (BOOKING_ID),
    FOREIGN KEY (PAT_ID) REFERENCES PATIENT(PAT_ID)
);

-- Create Vaccination Table
CREATE TABLE VACCINATION (
    BOOKING_ID NUMERIC,
    VAC_TYPE VARCHAR(10),
    VAC_DOSE NUMERIC,
    MCARE_NUM NUMERIC,
    PRIMARY KEY (BOOKING_ID),
    CONSTRAINT VAC_TYPE CHECK (VAC_TYPE IN ('Covid', 'Polio', 'Measles'))
);

-- Create Appointment Table
CREATE TABLE APPOINTMENT (
    BOOKING_ID NUMERIC,
    PAT_TYPE VARCHAR(10),
    PRIMARY KEY (BOOKING_ID),
    CONSTRAINT PAT_TYPE CHECK (PAT_TYPE IN ('Checkup', 'Treatment'))
);

-- Create Centre Table
CREATE TABLE CENTRE (
    C_ID NUMERIC,
    C_NAME CHAR(10),
    C_ADD CHAR(40),
    C_NUM CHAR(12),
    C_FAX CHAR(12),
    C_PRC_MGR CHAR(10),
    PRIMARY KEY (C_ID)
);

-- Create Timing Table
CREATE TABLE TIMING (
    DAYS VARCHAR(10),
    C_ID NUMERIC,
    OPENING_HOUR TIME,
    CLOSING_HOUR TIME,
    PRIMARY KEY (DAYS),
    FOREIGN KEY (C_ID) REFERENCES CENTRE(C_ID)
);

-- Create Doctor Table
CREATE TABLE DOCTOR (
    DOC_ID NUMERIC,
    C_ID NUMERIC,
    DOC_NAME VARCHAR(10),
    DOC_NUM CHAR(12),
    DOC_SOURCE VARCHAR(10),
    PRIMARY KEY (DOC_ID),
    FOREIGN KEY (C_ID) REFERENCES CENTRE(C_ID)
);

-- Create Manager History Table
CREATE TABLE MANAGER_HISTORY (
    C_ID NUMERIC,
    DATE_ASSIGN DATE,
    PRIMARY KEY (C_ID)
);


-- MedicalOne Database Schema

-- Patient Table
CREATE TABLE PATIENT (
    PAT_ID INT PRIMARY KEY,
    PAT_NAME VARCHAR(255),
    PAT_ADD VARCHAR(255),
    PAT_NUM VARCHAR(20)
);

-- Centre Table
CREATE TABLE CENTRE (
    C_ID INT PRIMARY KEY,
    C_NAME VARCHAR(255),
    C_ADD VARCHAR(255),
    C_OPENING_HOURS VARCHAR(255), -- Note: This should be normalized
    C_NUM VARCHAR(20),
    C_FAX VARCHAR(20),
    C_PRC_MGR VARCHAR(255) -- Note: This should have a history entity
);

-- Doctor Table
CREATE TABLE DOCTOR (
    DOC_ID INT PRIMARY KEY,
    DOC_NAME VARCHAR(255),
    DOC_NUM VARCHAR(20),
    DOC_SOURCE VARCHAR(255) -- Hired by MedicalOne or Allied Health
);

-- Booking Table
CREATE TABLE BOOKING (
    BOOKING_ID INT PRIMARY KEY,
    PAT_ID INT,
    DOC_ID INT,
    DATE DATE,
    TIME TIME,
    FOREIGN KEY (PAT_ID) REFERENCES PATIENT(PAT_ID),
    FOREIGN KEY (DOC_ID) REFERENCES DOCTOR(DOC_ID)
);

-- Vaccinations Table
CREATE TABLE VACCINATIONS (
    BOOKING_ID INT PRIMARY KEY,
    VAC_TYPE VARCHAR(255),
    VAC_DOSE VARCHAR(255),
    MCARE_NUM VARCHAR(20), -- Medicare number
    FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID)
);

-- Appointments Table
CREATE TABLE APPOINTMENTS (
    BOOKING_ID INT PRIMARY KEY,
    PAT_TYPE VARCHAR(255), -- General checkup or specific reason
    FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID)
);

-- Timings Table
CREATE TABLE TIMINGS (
    DAY VARCHAR(10) PRIMARY KEY, -- Days of the week
    OPENING_HOUR TIME,
    CLOSING_HOUR TIME
);

-- Manager History Table
CREATE TABLE MGR_HIST (
    C_ID INT,
    DATE_ASSIGN DATE,
    PRIMARY KEY (C_ID, DATE_ASSIGN),
    FOREIGN KEY (C_ID) REFERENCES CENTRE(C_ID)
);