-- Update Manager History Table
UPDATE MANAGER_HISTORY 
SET EMP_NUM = 432 
WHERE C_ID = 3189;

-- Queries
SELECT T.DAYS, C.C_PRC_MGR
FROM TIMING T  
JOIN CENTRE C ON T.C_ID = C.C_ID 
ORDER BY T.DAYS DESC;

SELECT T.DAYS, C.C_PRC_MGR 
FROM TIMING T  
JOIN CENTRE C ON T.C_ID = C.C_ID  
WHERE T.DAYS IN ('Tuesday', 'Friday', 'Saturday', 'Sunday') 
ORDER BY T.DAYS DESC;

UPDATE BOOKING  
SET BOOKING_DATE = CURDATE() 
WHERE PAT_ID = 003;

SELECT * FROM BOOKING;